lib{z}: {h c}{upstream/*}

c.poptions =+ "-I$src_base/upstream"
objs{*}: c.poptions += -DZLIB_DLL

lib{z}: cc.export.poptions = "-I$src_base/upstream"
libs{z}: c.export.poptions += -DZLIB_DLL

h{*}: install = false
for h: zlib zconf
  upstream/h{$h}@./upstream/: install = include/
